### PR TITLE
EPANET-MSX Low-Level API and Refactoring

### PR DESCRIPTION
**Pull request by karrowood**
Hello, my name is Kyle Arrowood, this summer I was given the opportunity to intern at Xylem where I was given the task to redesign the EPANET-MSX toolkit. The goal of this redesign was to remove dependencies on EPANET as well as dependencies
on the specific input files (.inp and .msx) meanwhile maintaining full backwards compatibility.

This is the current progress of the new MSX API redesign. I have put a lot of the specific information about the new structure in the Updates section of the new [Readme](https://github.com/karrowood/epanet-msx/blob/feature-api-augment/Readme.md). 

I look forward to discussion about the changes made!

### CODE REVIEW

**Comment by samhatchett** [comment]
The goals of this refactoring were pretty straightforward:

- maintain full CLI backward compatibility
- maintain full API backward compatibility
- decouple the core functionality from dependency on EPANET
  - allow safe programmatic creation/mutation of network data
  - allow safe programmatic injection of Hydrualic results data

This is a "very large" PR, as it must be to achieve the goals - however the heaviest lift was simply moving functions around to reorganize the code around the above principles.

I will be more formally reviewing the code over the next week, and I invite others so inclined to join as well. Using this PR thread as a way to anchor conversations will help us track whether we are meeting these goals.

**Comment by LRossman** [comment]
Nice job @karrowood . The re-organization of the code was well thought out and it appears that your objectives have been met. I do have a couple of suggestions that I think can improve things with little extra effort:

1. Make the reference to the `MSXproject `struct passed into each API function an opaque pointer instead of a direct one. That will better encapsulate the project data and avoid the need to distribute _msxtypes.h_ with the library. (Consult the [EPANET 2.2 code](https://github.com/openwateranalytics/epanet) to see how it was done there.)
 
2. To reduce the amount of memory allocation in the `MSXadd `functions consider allocating memory for the Node, Link, and concentration arrays in batches whose size doubles each time their current capacity is reached. Also consider adding an `MSXsetSize `function that allows one to set the initial size of these vectors.

**Comment by samhatchett** [comment]
thanks for the quick thoughts @LRossman - much appreciated. I had to laugh about the second item, because Kyle had originally implemented `MSXadd` in exactly that way (double size when capacity is reached) and I thought it looked like premature optimization ;) And I can conjure up cases where you'll be consuming almost 2x the memory needed -- however, I really like the idea of adding a `MSXsetSize` function to allow a client to hint at an allocation size, in much the way `std::vector` allocation works.

**Comment by karrowood** [comment]
Thanks for the feedback @LRossman, I checked out the EPANET 2.2 code and see that since the msxtypes.h will not be included in with the CLI that I should probably also create something like a msxenums.h, and also I will switch the implementation back to the more dynamic allocation that doubles every time that it reaches capacity.

**Comment by LRossman** [comment]
Here's a blueprint for implementing my first suggestion about using opaque pointers (not tested so user beware):
1. As mentioned, select all of the relevant enums in _msxtypes.h_ and cut and paste them to a new file _msxenums.h_. Add an include statement for this file in _msxtypes.h_ and _coretoolkit.h_. Remove the `#include msxtypes` statement from _coretoolkit.h_ and _legacytoolkit.h_.
2. Re-define the MSXproject struct in _msxtypes.h_ as:
```
typedef struct Project {
...
} *MSXproject;
```
3. Add `typedef struct Project *MSXproject;` to the top of coretoolkit.h.
4. Do a global Find and Replace operation on all files, replacing `(MSXproject *MSX` with `(MSXproject MSX`.
5. Restore the `MSXproject *MSX` signature to `MSX_open()` and place the following code at the top of it:
```
struct Project *p = (struct Project *) calloc(1, sizeof(struct Project));
*MSX = p;
```
6. Add `free(MSX)` to the bottom of `MSX_close()`.

If I messed up somewhere I'm sure that @samhatchett will correct it.

**Comment by karrowood** [comment]
I have updated the code, it now uses an opaque pointer for the MSXproject structure rather than a direct pointer. I have also created a new toolkit function called MSXsetSize that sets the size of the arrays within the MSXproject data structure. This function is also used within the adder functions whenever there is not enough space to add an object. 

I had a short discussion with @samhatchett, and have not yet implemented the doubling array sizes to save time. Sam believes that there are cases where extreme amounts of memory will be wasted for example when adding a 250,000th node and the size were to double up to 500,000. I see the advantages of doubling array sizes as it will save a lot of time during the allocation process. I am open to discussion about whether or not we should change this from the way it is currently implemented. The change is very trivial.

**Comment by samhatchett** [comment]
thanks @karrowood - yes, I think that size-doubling can be problematic in some cases. I figure that the client code will probably know how big the network is going to be, and anything else is probably a rare use case...

**Comment by LRossman** [comment]
I'm OK with keeping the incremental dynamic vector resizing as currently implemented. But I have a different question regarding the code that adds a new Node or Link to a project. I don't see where the arrays for `c` and `c0` get allocated for the new Node or Link. They do get allocated if a new species is added, but it seems not so when species already exist. Am I missing something?

BTW, allocation of the `c` arrays for nodes can be postponed until a simulation begins since they hold computed values, not input values.

**Comment by karrowood** [comment]
Previously all of the c and c0 values were allocated when adding species, but I just changed it to where the c values are allocated after everything has been added and MSX_init() is called. Now the c0 values are allocated with in addNode/addLink or addSpecies, just whichever one gets called second. Now the toolkit functions are not as strict in terms of order since now a user could either add species first or add the network first.

**Comment by samhatchett** [comment]
Just a note here that Kyle has completed his internship with Xylem, and we thank him for the valuable contribution to the codebase in the form of this pull request. I have been slower than usual to personally review the work here (which is saying something!), but will be devoting some time in the coming week. Just wanted to re-open the floor to other developers and engineers for comment. Thanks!!

**Comment by samhatchett** [comment]
Given that there are no other comments, I think this is ready for merge into dev as a major step toward expanding the integration opportunities for msx. I've looked this code over and have no objections. I'm sure we will generate some great ideas branching off from here.

**Review by samhatchett — APPROVED** [review]

**Pull request merged**
